// グレープシミュレーターのことば（日本語と英語）。index.html で、いちばん先に読みこむ。
// プログラムの中の言葉は日本語で書いてあって、GrapeLang.t('ブドウ') のように通すと、英語のときは下の EN の言葉になる。
// {name} のような所には、あとから名前や数字が入る。EN に無い言葉は、日本語のまま出る。
// index.html の data-i18n がついた所は、apply() で書きかえる（data-i18n-aria は読み上げ用の名前、data-i18n-ph は入力の見本の文字）。
(() => {
'use strict';
const KEY = 'grape-simulator-lang';
// 日本語 → 英語。画面の言葉を足したり変えたりしたら、ここにも書く（書かなかった言葉は、英語のときも日本語のまま出る）
const EN = {
  "ブドウ": "Grape",
  "マスカット": "Muscat",
  "イチゴ": "Strawberry",
  "ロボ": "Robot",
  "バナナ": "Banana",
  "パイナップル": "Pineapple",
  "ゾンビ": "Zombie",
  "ゴールドロボ": "Gold Robot",
  "グラウンド": "Field",
  "ひろい平地": "Wide, flat ground",
  "まち": "Town",
  "ビルの上から落とせる。坂で屋上へ": "Drop things off buildings. Ramp up to the roofs",
  "さか道": "Hills",
  "のりもので ジャンプ": "Jump with vehicles",
  "エンドレス": "Endless",
  "どこまでも続く。のりもので遠くへ": "It goes on forever. Drive as far as you can",
  "タワー": "Tower",
  "高い所から落とせる": "Drop things from up high",
  "うみ": "Sea",
  "水にうかぶ・しずむ": "Things float or sink",
  "火山": "Volcano",
  "溶岩に落とすと燃える。ときどき噴火": "Things burn in lava. Sometimes it erupts",
  "じっけん室": "Lab",
  "トゲと、かべと天井": "Spikes, walls, and a ceiling",
  "うちゅう": "Space",
  "重力が弱い": "Low gravity",
  "ガキッ": "Clank!",
  "ボキッ": "Snap!",
  "バキン": "Clang!",
  "ブチッ": "Rip!",
  "こわれた…": "Broken...",
  "死んだ…": "Dead...",
  "ゾンビ復活！": "The zombie rises!",
  "生き返った！": "Revived!",
  "元気になった！": "Healed!",
  "ナイフ": "Knife",
  "刀": "Katana",
  "ハンマー": "Hammer",
  "おの": "Axe",
  "やり": "Spear",
  "チェーンソー": "Chainsaw",
  "ピストル": "Pistol",
  "マシンガン": "Machine gun",
  "ロケットランチャー": "Rocket launcher",
  "爆弾": "Bomb",
  "ばくはつ樽": "Explosive barrel",
  "手りゅう弾": "Grenade",
  "車": "Car",
  "トラック": "Truck",
  "バイク": "Motorbike",
  "戦車": "Tank",
  "木箱": "Crate",
  "ドラム缶": "Oil drum",
  "ボール": "Ball",
  "鉄球": "Iron ball",
  "回復の注射": "Healing syringe",
  "トランポリン": "Trampoline",
  "風船": "Balloon",
  "ジュッ": "Sizzle!",
  "あちっ！": "Hot!",
  "噴火！": "Eruption!",
  "うわっ": "Whoa!",
  "キャラ": "Characters",
  "スワイプして画面に出す。タップすると空いている所に出る。": "Swipe one onto the screen to place it. Tap it to drop it in an open spot.",
  "ぶき": "Weapons",
  "刃のほうが当たると切れる。刃先からまっすぐ刺すと、刺さる（引っぱると抜ける）。": "The blade side cuts. Stab tip-first and it sticks (pull to get it out).",
  "じゅう": "Guns",
  "出した銃をタップすると撃つ。マシンガンはもう一度タップすると止まる。": "Tap a gun to fire it. Tap the machine gun again to stop it.",
  "ばくだん": "Bombs",
  "出した爆弾をタップすると火がつく。ばくはつ樽は強くぶつけても爆発する。": "Tap a bomb to light it. Explosive barrels also blow up when they hit something hard.",
  "のりもの": "Vehicles",
  "キャラをつかんで座席の近くではなすと乗る。のりものをタップすると走る・止まる。戦車は砲台をタップすると撃つ。": "Drop a character near a seat to put them in. Tap a vehicle to go or stop. Tap the tank's turret to fire.",
  "もの": "Things",
  "回復の注射の針を刺すとケガが治る。頭がついていれば、死んでいても生き返る。風船は、つかんでさわらせると、ひもでつながる。": "Stick the syringe's needle in to heal. If the head is still on, it even brings the dead back. Touch a balloon to something to tie it on.",
  "モッド": "Mods",
  "モッドエディターで作ったキャラや物。「＋ 作る」で新しく作れる。": "Characters and things made in the Mod Editor. Tap \"+ Make\" to make a new one.",
  "＋ 作る": "+ Make",
  "🔒 にじ色": "🔒 Rainbow",
  "🌈 にじ色": "🌈 Rainbow",
  "何もない所をドラッグすると画面が動く。2本指でアップ・ルーズ": "Drag an empty spot to move around. Pinch with two fingers to zoom",
  "何もない所をドラッグすると画面が動く。ホイールでアップ・ルーズ": "Drag an empty spot to move around. Use the mouse wheel to zoom",
  "あまいバナナの人": "A sweet banana person",
  "かたい皮で、1.5倍丈夫": "Hard skin makes it 1.5x as tough",
  "死んでも、頭がついていれば起き上がる": "Gets back up after dying, as long as its head is on",
  "ロボよりもっと丈夫な、金ぴかロボ": "A shiny gold robot, even tougher than Robot",
  "重くて、手足を切り落としやすい": "Heavy, and good at chopping off arms and legs",
  "長くて、深く刺さる": "Long, and stabs deep",
  "タップで動く。当てると切れつづける": "Tap to start it. It keeps cutting while it touches",
  "タップでピンをぬくと、2秒で爆発": "Tap to pull the pin. It explodes 2 seconds later",
  "タップでロケットを発射。当たると爆発": "Tap to fire a rocket. It explodes when it hits",
  "乗って走れる。砲台をタップすると大砲": "You can ride it. Tap the turret to fire the cannon",
  "上に落ちると、ボヨーンとはねる": "Land on it and boing, up you go",
  "ひもでつなぐと、うく。5こでキャラもうく": "Tie it on and things float. 5 of them lift a character",
  "にじ色の血": "Rainbow blood",
  "せっていで、血をにじ色にできる": "Make blood rainbow-colored in Settings",
  "キャラを30回出す": "Spawn characters 30 times",
  "骨を20本おる": "Break 20 bones",
  "ナイフや刀を15回刺す": "Stab with knives or katanas 15 times",
  "手足を15本とる": "Cut off 15 arms or legs",
  "銃を300発うつ": "Fire 300 shots",
  "爆発を40回おこす": "Set off 40 explosions",
  "50体たおす": "Defeat 50 characters",
  "キャラをのりものに10回乗せる": "Put characters in vehicles 10 times",
  "のりもので20回ひく": "Run over characters 20 times",
  "注射で10回生き返らせる": "Revive characters with the syringe 10 times",
  "高い所から落として15体たおす": "Defeat 15 characters by dropping them from up high",
  "水に30回とびこませる": "Make characters dive into water 30 times",
  "溶岩に10回落とす": "Drop characters into lava 10 times",
  "エンドレスで500m進む": "Go 500m in Endless",
  "エンドレスで2000m進む": "Go 2000m in Endless",
  "ぜんぶのマップ（9つ）で遊ぶ": "Play on all 9 maps",
  "1回の爆発で5体いっぺんにたおす": "Defeat 5 characters with one explosion",
  "1体の手足を4本ぜんぶとる": "Cut off all 4 arms and legs of one character",
  "500体たおす": "Defeat 500 characters",
  "ショップで3つ買う": "Buy 3 things in the shop",
  "モッドを3つ作る": "Make 3 mods",
  "戦車の大砲を20回うつ": "Fire the tank's cannon 20 times",
  "モッドを売りに出す": "Put a mod up for sale",
  "自分のモッドが売れる（お礼コードを読みこむ）": "Sell one of your mods (read a thank-you code)",
  "友だちのモッドを買う": "Buy a friend's mod",
  "100体たおす": "Defeat 100 characters",
  "爆発を30回おこす": "Set off 30 explosions",
  "手足を20本とる": "Cut off 20 arms or legs",
  "クエストクリア！「{quest}」 +🪙{coins}": "Quest cleared! \"{quest}\" +🪙{coins}",
  "{name}を手に入れた！": "You got {name}!",
  "GRAPEPAY1: で始まるお礼コードをはってね": "Paste a thank-you code that starts with GRAPEPAY1:",
  "コードが長すぎます": "The code is too long",
  "コードが読めません（とちゅうで切れているかも）": "Can't read the code (part of it may be missing)",
  "コードがまちがっています（どこかが変わっているかも）": "The code is wrong (something in it may have changed)",
  "これは、ほかの人のモッドのお礼コードだよ": "This is a thank-you code for someone else's mod",
  "このお礼コードは、もう使ったよ": "This thank-you code was already used",
  "{buyer}さんが「{name}」を買ってくれた！ +🪙{price}": "{buyer} bought your \"{name}\"! +🪙{price}",
  "だれか": "Someone",
  "✓ もってる": "✓ Owned",
  "あと🪙{n}": "Need 🪙{n} more",
  "ほんとうに買う？": "Really buy?",
  "つくった人：{by}": "Made by {by}",
  "💌 お礼コード": "💌 Thank-you code",
  "まだ何もならんでいないよ。": "Nothing here yet.",
  "🛠 モッドショップ": "🛠 Mod Shop",
  "友だちが売っているモッドを、コインで買えるよ。友だちから売り物のコードをもらって「コードを読みこむ」にはると、ここにならぶ。買ったら「お礼コード」を、作った人にわたしてね。": "Buy mods your friends are selling, with coins. Get a for-sale code from a friend and paste it into \"Read a code\" to put the mod here. After you buy one, give the \"thank-you code\" to its maker.",
  "📋 コードを読みこむ": "📋 Read a code",
  "「{name}」を買ったよ！ このお礼コードを、作った人（{by}）にわたしてね。作った人が読みこむと、🪙{price} がとどくよ。": "You bought \"{name}\"! Give this thank-you code to its maker ({by}). When they read it, they get 🪙{price}.",
  "クリア {done} / {total}": "Cleared {done} / {total}",
  "（くりかえし・{n}回クリア）": " (repeats, cleared {n} times)",
  "クリア": "Cleared",
  "テスト用：+🪙1000": "Test: +🪙1000",
  "フルーツ": "Fruit",
  "顔なし": "No face",
  "ふつう": "Normal",
  "刃": "Blade",
  "銃": "Gun",
  "回復の針": "Healing needle",
  "かるい": "Light",
  "おもい": "Heavy",
  "もろい": "Fragile",
  "丈夫": "Tough",
  "すごく丈夫": "Very tough",
  "なし": "Off",
  "あり": "On",
  "ななしのモッド": "Untitled mod",
  "モッドのデータではありません": "This isn't mod data",
  "キャラか物か、わかりません": "Can't tell if it's a character or a thing",
  "色のデータがおかしいです": "The color data is broken",
  "絵が何もかいてありません": "Nothing is drawn",
  "絵のデータがおかしいです": "The picture data is broken",
  "保存できませんでした": "Couldn't save",
  "モッドは60こまでだよ": "You can have up to 60 mods",
  "「{name}」がショップにならんだ！ 🪙{price}で買えるよ": "\"{name}\" is in the shop now! You can buy it for 🪙{price}",
  "「{name}」を新しくした！": "Updated \"{name}\"!",
  "「{name}」を読みこんだ！": "Loaded \"{name}\"!",
  "モッドのコード（GRAPEMOD1:）か、お礼コード（GRAPEPAY1:）をはってね": "Paste a mod code (GRAPEMOD1:) or a thank-you code (GRAPEPAY1:)",
  "モッドのファイルではありません": "This isn't a mod file",
  "キャラクター": "Character",
  "物・{kind}": "Thing: {kind}",
  "🛠 モッドエディター": "🛠 Mod Editor",
  "自分でキャラや物を作れるよ。作ったモッドは、アイテムのひきだしの「モッド」に出てくる。コードをコピーして友だちにわたしたり、値段をつけて売ったりもできる。": "Make your own characters and things. Your mods show up in the \"Mods\" tab of the item drawer. You can copy a code to give a mod to a friend, or put a price on it and sell it.",
  "＋ キャラを作る": "+ New character",
  "＋ 物を作る": "+ New thing",
  "📁 ファイルを読みこむ": "📁 Load a file",
  "まだモッドがないよ。上のボタンで作ってみよう！": "No mods yet. Make one with the buttons above!",
  "🪙{price}で売り中・{n}こ売れた": "On sale for 🪙{price}, {n} sold",
  "🔒 🪙{price}（ショップで買える）": "🔒 🪙{price} (buy it in the shop)",
  "✓ 買った": "✓ Bought",
  "🛒 ショップへ": "🛒 To the shop",
  "✏ なおす": "✏ Edit",
  "▶ ためす": "▶ Try",
  "📋 コード": "📋 Code",
  "💾 ファイル": "💾 File",
  "💰 売る": "💰 Sell",
  "🗑 けす": "🗑 Delete",
  "ほんとうに消す？": "Really delete?",
  "📋 コピー": "📋 Copy",
  "コピーできなかったので、文字をえらんでコピーしてね": "Couldn't copy. Select the text and copy it yourself",
  "コピーした！ 友だちにわたしてね": "Copied! Now give it to a friend",
  "とじる": "Close",
  "このコードを友だちにわたすと、同じモッドを読みこめるよ。": "Give this code to a friend, and they can load the same mod.",
  "売り物のコードだよ（🪙{price}）。友だちが読みこむと、ショップにならぶ。友だちが買ってくれたら、もらったお礼コードを「コードを読みこむ」にはってね。": "This is a for-sale code (🪙{price}). When a friend reads it, the mod shows up in their shop. When they buy it, paste the thank-you code they give you into \"Read a code\".",
  "売り物のモッドなので、このコードを読みこんだ人は、ショップで買うと使えるよ。": "This mod is for sale. Anyone who reads this code can use it after buying it in the shop.",
  "「{name}」のコード": "Code for \"{name}\"",
  "コードを読みこむ": "Read a code",
  "モッドのコード（GRAPEMOD1:）か、お礼コード（GRAPEPAY1:）を、ここにはりつけてね": "Paste a mod code (GRAPEMOD1:) or a thank-you code (GRAPEPAY1:) here",
  "読みこむ": "Read",
  "やめる": "Cancel",
  "💰「{name}」を売る": "💰 Sell \"{name}\"",
  "なまえ": "Name",
  "値段を変える": "Change the price",
  "売りに出す": "Put it up for sale",
  "売るのをやめる": "Stop selling",
  "ほんとうに？": "Really?",
  "「{name}」を売るのをやめた": "Stopped selling \"{name}\"",
  "値段をえらんで「売りに出す」をおすと、売り物のコードが出るよ。それを友だちにわたしてね。友だちがショップで買うと「お礼コード」をくれるので、それを「コードを読みこむ」にはると、コインがもらえる。": "Pick a price and press \"Put it up for sale\" to get a for-sale code, then give it to your friends. When a friend buys the mod in the shop, they give you a \"thank-you code\". Paste it into \"Read a code\" to get your coins.",
  "あなたの名前（買う人に見える）": "Your name (buyers see it)",
  "値段": "Price",
  "ファイルが大きすぎます": "The file is too big",
  "わたしのキャラ": "My character",
  "わたしの物": "My thing",
  "「{name}」を保存した！": "Saved \"{name}\"!",
  "物": "Thing",
  "💾 ほぞん": "💾 Save",
  "✕ やめる": "✕ Quit",
  "ほんとうにやめる？": "Really quit?",
  "✏ ペン": "✏ Pen",
  "🧽 けしゴム": "🧽 Eraser",
  "🪣 ぬりつぶし": "🪣 Fill",
  "↩ もどす": "↩ Undo",
  "🗑 ぜんぶけす": "🗑 Clear all",
  "ほかの色": "Other color",
  "顔": "Face",
  "肌": "Skin",
  "服": "Shirt",
  "りんかく": "Outline",
  "血": "Blood",
  "丈夫さ": "Toughness",
  "重さ": "Weight",
  "ロボみたいに、オイルと火花": "Oil and sparks, like a robot",
  "赤い四角の中が顔。うすい黒い点の所に、目と口が出る。": "The face goes inside the red square. The eyes and mouth go on the faint dots.",
  "はば": "Width",
  "たかさ": "Height",
  "しゅるい": "Kind",
  "はねる強さ": "Bounciness",
  "刃のはじまり（赤い線から右が刃）": "Blade start (right of the red line is the blade)",
  "右が刃先。刃先からまっすぐ当てると刺さる。": "The tip is on the right. Hit tip-first to stab.",
  "いりょく": "Power",
  "れんしゃ": "Rapid fire",
  "いちばん右はしから弾が出る。出した銃をタップすると撃つ。": "Bullets come out of the right edge. Tap the gun to fire.",
  "爆発までの時間（びょう）": "Time until it explodes (seconds)",
  "出した爆弾をタップすると、火がつく。": "Tap the bomb to light it.",
  "まるい物として、ころがる。": "It rolls like something round.",
  "いちばん右の3列が針。針をキャラに刺すと、ケガが治る。": "The 3 rightmost columns are the needle. Stick it into a character to heal them.",
  "色は24色までだよ": "You can use up to 24 colors",
  "ルーズ": "Zoom out",
  "アップ": "Zoom in",
  "スマホを横にしてね": "Turn your phone sideways",
  "グレープ": "Grape",
  "シミュレーター": "Simulator",
  "▶ プレイ": "▶ Play",
  "📜 クエスト": "📜 Quests",
  "🛒 ショップ": "🛒 Shop",
  "🛠 モッド": "🛠 Mods",
  "⚙ せってい": "⚙ Settings",
  "ブラウザ版": "Browser version",
  "コインは、クエストをクリアしたり、キャラをたおしたりすると、もらえる。いま": "You get coins by clearing quests and defeating characters. You have",
  "← もどる": "← Back",
  "クリアすると、コインがもらえる。コインはショップで使える。": "Clear quests to get coins. Spend your coins in the shop.",
  "マップをえらぶ": "Choose a map",
  "← ホーム": "← Home",
  "せってい": "Settings",
  "あなたの名前（モッドを売り買いするときに出る）": "Your name (shown when you buy or sell mods)",
  "血の量": "Amount of blood",
  "多め": "Lots",
  "血の色": "Blood color",
  "ケガのしやすさ": "How easily they get hurt",
  "キャラの大きさ（はじめのズーム）": "Character size (starting zoom)",
  "小さい": "Small",
  "大きい": "Big",
  "出てくる向き": "Facing when they appear",
  "ランダム": "Random",
  "右": "Right",
  "左": "Left",
  "音楽": "Music",
  "小さめ": "Quiet",
  "効果音": "Sound effects",
  "大きめ": "Loud",
  "アイテム": "Items",
  "スロー": "Slow motion",
  "一時停止": "Pause",
  "ぜんぶ消す": "Clear everything",
  "全画面": "Full screen",
  "マップ": "Maps",
  "左に回す": "Turn left",
  "右に回す": "Turn right",
  "グレープシミュレーター": "Grape Simulator",
};

// はじめは、ブラウザのことばに合わせる（日本語のブラウザなら日本語、それ以外は英語）。えらんだら保存する
let lang = /^ja\b/i.test(navigator.language || '') ? 'ja' : 'en';
try { const s = localStorage.getItem(KEY); if (s === 'ja' || s === 'en') lang = s; } catch (e) { /* 保存できないブラウザでも動く */ }
const missing = new Set();   // 英語が見つからなかった言葉（テスト用）
function t(ja, vars) {
  let s = ja;
  if (lang === 'en') {
    if (Object.prototype.hasOwnProperty.call(EN, ja)) s = EN[ja];
    else if (/[ぁ-ヿ㐀-鿿]/.test(ja)) missing.add(ja);   // 日本語が入っているのに、英語が無い
  }
  return vars ? s.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m)) : s;
}
function apply(root = document.body) {
  document.documentElement.lang = lang;
  document.title = t('グレープシミュレーター');
  for (const e of root.querySelectorAll('[data-i18n]')) {
    if (!e.dataset.i18n) e.dataset.i18n = e.textContent.trim();   // はじめに書いてあった日本語をおぼえておく
    e.textContent = t(e.dataset.i18n);
  }
  for (const e of root.querySelectorAll('[data-i18n-aria]')) {
    if (!e.dataset.i18nAria) e.dataset.i18nAria = e.getAttribute('aria-label') || '';
    e.setAttribute('aria-label', t(e.dataset.i18nAria));
  }
  for (const e of root.querySelectorAll('[data-i18n-ph]')) {
    if (!e.dataset.i18nPh) e.dataset.i18nPh = e.getAttribute('placeholder') || '';
    e.setAttribute('placeholder', t(e.dataset.i18nPh));
  }
}
const listeners = [];
function set(l) {
  if ((l !== 'ja' && l !== 'en') || l === lang) return;
  lang = l;
  try { localStorage.setItem(KEY, l); } catch (e) { /* 同上 */ }
  apply();
  for (const fn of listeners) fn(l);
}
window.GrapeLang = {
  t, apply, set,
  lang: () => lang,
  onChange: (fn) => { listeners.push(fn); },
  missing: () => [...missing],
  words: () => Object.keys(EN),   // テスト用
};
apply();
})();
